# Create environment:
#   conda env create --file environment.yml
# Remove environment:
#   conda remove --name fys-stk4155 --all

name: fys-stk4155

channels:
  - conda-forge

dependencies:
  - python>=3.12
  - pip
  - cython

  - pip:
    - -r requirements.txt
